### ISSUE TITLE
Python examples cache.py error

### ISSUE THREAD

**Issue by swarmt** [PRBonn/vdbfusion#16]
`args_to_key()` is missing the `ignore` parameter.

https://github.com/PRBonn/vdbfusion/blob/8d01832419050aed1105e666040c4e5d3a14c96c/examples/python/utils/cache.py#L38

**Comment by nachovizzo** [comment]
Good catch,  they added this feature [on a newer version](https://github.com/grantjenks/python-diskcache/pull/226). I'm working to see if I can integrate this into the utility and get rid of the duplicated code
