### ISSUE TITLE
Is there a plan for texture the mesh ? 

### ISSUE THREAD

**Issue by qpc001** [PRBonn/vdbfusion#17]

**Comment by nachovizzo** [comment]
If you mean for color? I'm actually not planning to integrate it anytime soon. Although I think @swarmt  had some ideas for this.

**Comment by swarmt** [comment]
I was thinking something like [this](https://github.com/swarmt/vdbfusion/blob/0d56a2ebc36b09fbc6cc8a7beeacb46eb449e731/src/vdbfusion/vdbfusion/VDBVolume.cpp)
That would give voxel color (facet from marching cubes), unfortunately open3d only supports vertex color (unless you are happy to hack the mesh into triangle soup). Have not thought of a good way to handle this yet.

**Comment by qpc001** [comment]
> 

Amazing work.

**Comment by gchhablani** [comment]
Is there a plan to integrate this any time soon?
