### ISSUE TITLE
why vdbfusion appears some trianglemesh where there is no point hit?

### ISSUE THREAD

**Issue by qpc001** [PRBonn/vdbfusion#19]
![hits](https://user-images.githubusercontent.com/31476516/169995155-740e497e-d0e6-4433-ab17-8d13f6912bb2.png)

**Comment by nachovizzo** [comment]
Could you please elaborate a bit more?

**Comment by qpc001** [comment]
> 你能详细说明一下吗？

Using the VLP-16 to build the mesh, the scene is looking like this:

![hit](https://user-images.githubusercontent.com/31476516/170181578-ef218811-457d-4dc4-a8b9-db46e3c49c25.png)

**Comment by qpc001** [comment]
> 好的，现在我明白了。这是因为 vdbfusion 使用了 TSDF，它代表了一个截断的有符号距离场。重建中之所以有“厚”的墙是因为截断值，较大的截断值会产生“更厚”的伪影，反之亦然。 您有 2 个选项：
> 
> 1. 减少截断值`sdf_trunc`
> 2. 禁用`filling_holes`标志，这也应该产生更薄的表面

When I go to the  other side of the wall,  it should be disappear, but it isn't.

**Comment by nachovizzo** [comment]
I'm sorry but I don't speak Chinese

**Comment by qpc001** [comment]
> You could probably check Directional TSDF [arxiv.org/pdf/1908.05146.pdf](https://arxiv.org/pdf/1908.05146.pdf)

Thank you.
