### ISSUE TITLE
Extrinsics in RGBD integration

### ISSUE THREAD

**Issue by Willyzw** [PRBonn/vdbfusion#2]
Hallo, while trying out the example for RGB-D image based integration, I notice that the extrinsic/global poses are inverted. Since normally the global poses are given as `camera to world`, shall I interpret the inverted pose as `world to camera` transformation?

Lets take an example, the global pose is inverted here for scannet dataset. 
https://github.com/PRBonn/vdbfusion/blob/40ad3021c271c26d638672531818f86d2c91d3b8/examples/python/datasets/scannet.py#L33

Then the RGBD point cloud is transformed using the inverted pose here
https://github.com/PRBonn/vdbfusion/blob/40ad3021c271c26d638672531818f86d2c91d3b8/examples/python/datasets/scannet.py#L61-L63

So far is fine, as I vaguely remember `open3d` indeed assumes an extrinsic from world to camera. However, this inverted pose is further fed to the integration pipeline then apparently regarded as the frame origin. I am wondering whether this is really the purpose?
https://github.com/PRBonn/vdbfusion/blob/40ad3021c271c26d638672531818f86d2c91d3b8/examples/python/datasets/scannet.py#L74

**Comment by Willyzw** [comment]
Thanks for the reply. Yes it solve my confusion. The interface expects the point clouds as well as the origins in global frame. Thus by contrast to `open3d`, which assumes an extrinsic pose from global to local frame, the dataloader needs to return normal `uninverted` pose.

**Comment by ShrutheeshIR** [comment]
Hey @Willyzw , I'm also trying to use an RGBD sensor instead of Lidar. Could you give a rough outline of steps you used. Thanks!
