### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by petergerten** [PRBonn/vdbfusion#23]
How would I query the map for collision detection?
Is there a way to use it with [fcl](https://github.com/flexible-collision-library/fcl) for example?

**Comment by nachovizzo** [comment]
That's a great question. I never looked into `fcl` myself. And I'm not an expert on the topic. I guess you could ask on the OpenVDB forums, or GitHub. Whatever you can do with OpenVDB then you will be able to integrate into VDBFusion :)
