### ISSUE TITLE
Worse results than the paper displayed

### ISSUE THREAD

**Issue by Rotatingpencil** [PRBonn/vdbfusion#24]
I'm running the kitti 00 sequence with python API, but I got the result below:
![image](https://user-images.githubusercontent.com/62542727/180419708-e778d76d-6847-49b8-a3fb-163d9f6492c9.png)
![image](https://user-images.githubusercontent.com/62542727/180419822-df39577e-2c70-410f-b09e-4270dd673826.png)

which is much worse than the paper displayed:

![image](https://user-images.githubusercontent.com/62542727/180419647-42394db3-e830-43c6-a3cd-273c001373cc.png)

I got this result without editing the config file.

And I repeated it by changing the ```fill_holes``` to True, but the result did not change.

Why there are two different results?

**Comment by Rotatingpencil** [comment]
For example, there are overlaps of cars and bumpy roads.

**Comment by nachovizzo** [comment]
Hello @Rotatingpencil, that looks like pose estimation errors. Usually the so-called "ground truth" poses from KITTI are not enough. You can give it a try with these poses:
[00.txt](https://github.com/PRBonn/vdbfusion/files/9167546/00.txt)

Just override the `00.txt` on your filesystem. Please let me know if this helps with the problem

**Comment by Rotatingpencil** [comment]
Now the result seems perfect! 

How can I get the correct poses that you sent me, the poses I used before were downloaded from the official website, but it's wrong....

**Comment by nachovizzo** [comment]
You can use any SLAM system, for example SuMa ;)
