### ISSUE TITLE
Dataset example for Argoverse v2?

### ISSUE THREAD

**Issue by changyuan79** [PRBonn/vdbfusion#25]
First, I'd like to thank you for creating a such nicely developed library and introducing me to OpenVDB! 

The Argoverse v2 dataset (https://www.argoverse.org/av2.html#sensor-link) was recently released. I wonder if you could provide a quick sample of Dataset and Pipeline, similar to the other ones (such as KITTI and nuScenes). Thank you again!

**Comment by nachovizzo** [comment]
Hello there, sorry for the late reply. I'm actually quite interested but have no time to do it now.... if you want go ahead and give it a try!
