### ISSUE TITLE
How to use the TUM RGBD dataset?

### ISSUE THREAD

**Issue by lin-name** [PRBonn/vdbfusion#38]
Dear professor,
 Thanks for your great work. I have compiled this code on Windows with VS2019, and run with the KITTI odometry dataset sequence 00, and get the right result consistent with your paper.   As i know, we can get the **Tr** form the calib.txt file of the KITTI, and get the final pose by:

`T_velo_cam * P * T_cam_velo`

Source code in KITTIOdometry.cpp:

![屏幕截图 2024-02-02 103831](https://github.com/PRBonn/vdbfusion/assets/65641960/c8291455-3c00-45bd-b795-8ef0b1e82248)

But how can i run it with the TUM RGBD dataset?  and how can i get the **Tr** of the TUM RGBD data.  I tried to set the **T_cam_vel**o and the **T_velo_cam** to **Eigen::Matrix4d::Identify()**, but the output is wrong.  

Looking forward for your reply.

**Comment by saurabh1002** [comment]
@lin-name, sorry for the late reply.

Unfortunately we do not provide cpp pipeline for TUM dataset. Modifying Kitti dataloader to work with TUM is not the best way to go ahead with it, as TUM provides RGBD images as the primary data.

You will have to re-implement a C++ dataloader for TUM, following the python dataloader [here](https://github.com/PRBonn/vdbfusion/blob/main/examples/python/datasets/tum.py)
I had written one for a different [project](https://github.com/saurabh1002/fusion_slam/tree/master/c%2B%2B_src/dataloaders/freiburg1_desk) which can also be a good starting point, although it is an old (not so clean) implementation.
