### ISSUE TITLE
make install not work.

### ISSUE THREAD

**Issue by qpc001** [PRBonn/vdbfusion#5]
make install not work.

**Comment by nachovizzo** [comment]
Can you please describe the issue? Please read the [Installation instructions](https://github.com/PRBonn/vdbfusion/blob/main/INSTALL.md) first

**Comment by YoshuaNava** [comment]
I have also experienced this issue.

Installing from pip3 works every time :heavy_check_mark:, *but* `sudo make install` doesn't seem to populate the `install_manifest.txt`, nor copy library files to the right locations..
